#!/usr/bin/env bash
set -euo pipefail

# Upload local screenshots to GitHub's user-attachments CDN via the `gh image`
# extension (drogers0/gh-image) and post them as one PR comment. The uploaded
# URLs are public github.com/user-attachments/assets/... links, so they render
# inline on the PR — no binaries committed to the app repo.
#
# Usage:
#   tools/post-pr-visual-evidence.sh <pr-number> [--repo owner/repo] \
#       [--title "Visual evidence"] <image-path> [<image-path> ...]
#
# Run from inside the task worktree so `gh` infers the pocketpal-ai repo and the
# image paths resolve. Requires the `gh image` extension and a GitHub session
# token (GH_SESSION_TOKEN env var, or a logged-in browser session it extracts)
# for the upload; the comment itself is posted as the bot via tools/ghb.
#
#   success            -> posts the comment, prints the comment URL, exits 0
#   missing/bad token  -> prints MANUAL_POST_REQUIRED + the exact hand-run
#                         command, exits 3 (caller records a pending condition
#                         instead of claiming the evidence was posted)
#   bad args / no tool -> exits 2

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

title="Visual evidence"
repo_args=()
pr=""
images=()

while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo)  repo_args=(--repo "$2"); shift 2 ;;
    --title) title="$2"; shift 2 ;;
    --)      shift; while [[ $# -gt 0 ]]; do images+=("$1"); shift; done ;;
    -*)      echo "Unknown flag: $1" >&2; exit 2 ;;
    *)       if [[ -z "$pr" ]]; then pr="$1"; else images+=("$1"); fi; shift ;;
  esac
done

if [[ -z "$pr" || ${#images[@]} -eq 0 ]]; then
  echo "usage: $0 <pr-number> [--repo owner/repo] [--title <t>] <image> [<image>...]" >&2
  exit 2
fi

if ! gh image --version >/dev/null 2>&1; then
  echo "FATAL: gh image extension not installed (gh extension install drogers0/gh-image)" >&2
  exit 2
fi

missing=0
for img in "${images[@]}"; do
  [[ -f "$img" ]] || { echo "FATAL: image not found: $img" >&2; missing=1; }
done
[[ $missing -eq 0 ]] || exit 2

manual_cmd="gh image ${repo_args[*]} ${images[*]}   # then paste the markdown into: $here/ghb pr comment $pr ${repo_args[*]} --body-file -"

# Honest degrade: verify a token works before uploading, so a tokenless headless
# run reports a pending manual post rather than a half-finished comment.
if ! gh image check-token ${repo_args[@]+"${repo_args[@]}"} >/dev/null 2>&1; then
  {
    echo "MANUAL_POST_REQUIRED: no valid GitHub session token for image upload."
    echo "  Captures (local, NOT yet on PR #$pr):"
    printf '    - %s\n' "${images[@]}"
    echo "  Post manually once a token is available (GH_SESSION_TOKEN or a logged-in browser):"
    echo "    $manual_cmd"
  } >&2
  exit 3
fi

refs="$(gh image ${repo_args[@]+"${repo_args[@]}"} "${images[@]}")" || {
  echo "MANUAL_POST_REQUIRED: gh image upload failed. Retry: $manual_cmd" >&2
  exit 3
}

body="## ${title}

${refs}

Generated by [PocketPal Dev Team](https://github.com/a-ghorbani/pocketpal-dev-team)"

"$here/ghb" pr comment "$pr" ${repo_args[@]+"${repo_args[@]}"} --body "$body" || {
  echo "MANUAL_POST_REQUIRED: PR comment failed (images are uploaded). Post by hand:" >&2
  echo "    $here/ghb pr comment $pr ${repo_args[*]} --body-file <file containing the markdown above>" >&2
  exit 3
}
echo "Posted ${#images[@]} image(s) to PR #$pr as the bot"
