#!/usr/bin/env python3
"""Generate per-harness adapters from the harness-neutral sources.

Sources (edit these):
  agents/<name>.md          frontmatter: name, description; body: the role
  skills/<name>/SKILL.md    Agent Skills format; name must equal the directory

Generated (never edit by hand):
  .claude/agents/<name>.md      Claude Code subagent
  .codex/agents/<name>.toml     Codex custom agent (Codex reads TOML only)
  .opencode/agents/<name>.md    opencode subagent
  .claude/skills/<name>  -> ../../skills/<name>   Claude Code
  .agents/skills/<name>  -> ../../skills/<name>   Codex + opencode

Usage: tools/sync-harness.py [--check]
  --check  exit 1 if any adapter is missing, stale, or orphaned; write nothing.
"""

from __future__ import annotations

import json
import os
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MARKER = "generated by tools/sync-harness.py from"

AGENT_DIRS = {
    "claude": ROOT / ".claude/agents",
    "codex": ROOT / ".codex/agents",
    "opencode": ROOT / ".opencode/agents",
}
SKILL_LINK_DIRS = [ROOT / ".claude/skills", ROOT / ".agents/skills"]


def parse_source(path: Path) -> tuple[str, str, str]:
    match = re.match(r"---\n(.*?)\n---\n(.*)", path.read_text(), re.S)
    if not match:
        sys.exit(f"{path}: missing frontmatter")
    front, body = match.groups()
    fields = {}
    for line in front.splitlines():
        key, _, value = line.partition(":")
        fields[key.strip()] = value.strip().strip('"')
    name, description = fields.get("name"), fields.get("description")
    if not name or not description:
        sys.exit(f"{path}: frontmatter needs name and description")
    if name != path.stem:
        sys.exit(f"{path}: name '{name}' must match the file name")
    return name, description, body.strip() + "\n"


def toml_multiline(text: str) -> str:
    if "'''" not in text:
        return "'''\n" + text + "'''"
    return json.dumps(text)


def render(name: str, description: str, body: str) -> dict[str, str]:
    source = f"agents/{name}.md"
    desc = json.dumps(description)
    claude = (
        f"---\n# {MARKER} {source}\nname: {name}\ndescription: {desc}\n"
        f"disallowedTools: Agent, Task\n---\n\n{body}"
    )
    codex = (
        f"# {MARKER} {source}\nname = {json.dumps(name)}\ndescription = {desc}\n"
        f"developer_instructions = {toml_multiline(body)}\n"
    )
    parsed = tomllib.loads(codex)
    if parsed["developer_instructions"] != body:
        sys.exit(f"{source}: TOML round-trip changed the body")
    opencode = (
        f"---\n# {MARKER} {source}\ndescription: {desc}\nmode: subagent\n"
        f"permission:\n  task: deny\n---\n\n{body}"
    )
    return {
        f".claude/agents/{name}.md": claude,
        f".codex/agents/{name}.toml": codex,
        f".opencode/agents/{name}.md": opencode,
    }


def expected_state() -> tuple[dict[str, str], dict[str, str]]:
    files: dict[str, str] = {}
    for src in sorted((ROOT / "agents").glob("*.md")):
        if src.name == "README.md":
            continue
        files.update(render(*parse_source(src)))

    links: dict[str, str] = {}
    for skill in sorted((ROOT / "skills").iterdir()):
        manifest = skill / "SKILL.md"
        if not manifest.is_file():
            continue
        declared = re.search(r"^name:\s*(\S+)", manifest.read_text(), re.M)
        if not declared or declared.group(1) != skill.name:
            sys.exit(f"{manifest}: name must be present and equal '{skill.name}'")
        for link_dir in SKILL_LINK_DIRS:
            links[str((link_dir / skill.name).relative_to(ROOT))] = f"../../skills/{skill.name}"
    return files, links


def is_generated(path: Path) -> bool:
    try:
        return MARKER in path.read_text(errors="ignore")[:400]
    except OSError:
        return False


def sync(check: bool) -> int:
    files, links = expected_state()
    drift: list[str] = []

    for rel, content in files.items():
        path = ROOT / rel
        if not path.exists() or path.read_text() != content:
            drift.append(f"stale   {rel}")
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)

    for directory in AGENT_DIRS.values():
        for path in directory.glob("*"):
            rel = str(path.relative_to(ROOT))
            if rel not in files and path.is_file() and (is_generated(path) or path.stem.startswith("pocketpal-")):
                drift.append(f"orphan  {rel}")
                if not check:
                    path.unlink()

    for rel, target in links.items():
        path = ROOT / rel
        if not path.is_symlink() or os.readlink(path) != target:
            drift.append(f"link    {rel} -> {target}")
            if not check:
                if path.is_symlink() or path.is_file():
                    path.unlink()
                elif path.is_dir():
                    sys.exit(f"{rel} is a real directory; move its contents into skills/ first")
                path.parent.mkdir(parents=True, exist_ok=True)
                path.symlink_to(target)

    for link_dir in SKILL_LINK_DIRS:
        for path in link_dir.glob("*"):
            rel = str(path.relative_to(ROOT))
            if path.is_symlink() and rel not in links:
                drift.append(f"orphan  {rel}")
                if not check:
                    path.unlink()

    for line in drift:
        print(line)
    if check and drift:
        print("harness adapters are out of date; run tools/sync-harness.py", file=sys.stderr)
        return 1
    if not drift:
        print("harness adapters up to date")
    return 0


if __name__ == "__main__":
    sys.exit(sync("--check" in sys.argv[1:]))
