#!/usr/bin/env python3
"""Wire the harness-neutral sources into each harness's discovery paths.

Sources (the only files to edit):
  agents/<name>.md          one role; frontmatter carries every harness's keys
  skills/<name>/SKILL.md    Agent Skills format; name must equal the directory

Wiring (created here; content never needs syncing):
  .claude/agents/<name>.md    -> ../../agents/<name>.md    Claude Code
  .opencode/agents/<name>.md  -> ../../agents/<name>.md    opencode
  .pi/agents/<name>.md        -> ../../agents/<name>.md    pi (via its subagent extension)
  .codex/agents/<name>.toml   stub pointing at agents/<name>.md (Codex reads TOML only)
  .claude/skills/<name>       -> ../../skills/<name>       Claude Code
  .agents/skills/<name>       -> ../../skills/<name>       Codex + opencode

Re-run after adding, renaming, or removing a role or skill, or after changing a
role's description. Editing a role's body or a skill needs no re-run.

Usage: tools/sync-harness.py [--check]
  --check  exit 1 if any wiring is missing, stale, or orphaned; change nothing.
"""

from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STUB_MARKER = "# stub generated by tools/sync-harness.py"


def frontmatter(path: Path) -> dict[str, str]:
    match = re.match(r"---\n(.*?)\n---\n", path.read_text(), re.S)
    if not match:
        sys.exit(f"{path}: missing frontmatter")
    fields = {}
    for line in match.group(1).splitlines():
        if line.startswith(" "):
            continue
        key, _, value = line.partition(":")
        value = value.strip()
        fields[key.strip()] = json.loads(value) if value.startswith('"') else value
    return fields


def codex_stub(name: str, description: str) -> str:
    return (
        f"{STUB_MARKER} from agents/{name}.md\n"
        f"name = {json.dumps(name)}\n"
        f"description = {json.dumps(description, ensure_ascii=False)}\n"
        f"developer_instructions = {json.dumps(f'Your role is defined in agents/{name}.md at the repository root. Read that file now and follow its body as your instructions; its frontmatter is harness configuration and can be ignored.')}\n"
    )


def expected() -> tuple[dict[str, str], dict[str, str]]:
    links: dict[str, str] = {}
    stubs: dict[str, str] = {}

    for src in sorted((ROOT / "agents").glob("*.md")):
        if src.name == "README.md":
            continue
        fields = frontmatter(src)
        name, description = fields.get("name"), fields.get("description")
        if name != src.stem or not description:
            sys.exit(f"{src}: needs description and name equal to '{src.stem}'")
        for harness in (".claude", ".opencode", ".pi"):
            links[f"{harness}/agents/{name}.md"] = f"../../agents/{name}.md"
        stubs[f".codex/agents/{name}.toml"] = codex_stub(name, description)

    for skill in sorted((ROOT / "skills").iterdir()):
        manifest = skill / "SKILL.md"
        if not manifest.is_file():
            continue
        if frontmatter(manifest).get("name") != skill.name:
            sys.exit(f"{manifest}: name must be present and equal '{skill.name}'")
        for harness in (".claude", ".agents"):
            links[f"{harness}/skills/{skill.name}"] = f"../../skills/{skill.name}"

    return links, stubs


def managed(path: Path) -> bool:
    if path.is_symlink():
        return True
    if path.suffix == ".toml" and path.is_file():
        return path.read_text(errors="ignore").startswith(STUB_MARKER)
    return path.is_file() and path.name.startswith("pocketpal-")


def sync(check: bool) -> int:
    links, stubs = expected()
    drift: list[str] = []

    for rel, target in links.items():
        path = ROOT / rel
        if path.is_symlink() and os.readlink(path) == target:
            continue
        drift.append(f"link    {rel} -> {target}")
        if check:
            continue
        if path.is_dir() and not path.is_symlink():
            sys.exit(f"{rel} is a real directory; move its contents into the source tree first")
        if path.exists() or path.is_symlink():
            path.unlink()
        path.parent.mkdir(parents=True, exist_ok=True)
        path.symlink_to(target)

    for rel, content in stubs.items():
        path = ROOT / rel
        if path.is_file() and path.read_text() == content:
            continue
        drift.append(f"stub    {rel}")
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    # pi loads an extension only from an explicit entry file; a directory path silently loads nothing.
    pi_entries = ["./.pi/extensions/guards/index.ts", "./.pi/extensions/subagent/index.ts"]
    try:
        listed = json.loads((ROOT / ".pi/settings.json").read_text()).get("extensions", [])
    except (OSError, ValueError):
        listed = []
    for entry in pi_entries:
        if entry not in listed:
            drift.append(f"config  .pi/settings.json must list {entry}")

    wanted = set(links) | set(stubs)
    for directory in (".claude/agents", ".opencode/agents", ".pi/agents", ".codex/agents", ".claude/skills", ".agents/skills"):
        for path in (ROOT / directory).glob("*"):
            rel = str(path.relative_to(ROOT))
            if rel not in wanted and managed(path):
                drift.append(f"orphan  {rel}")
                if not check:
                    path.unlink()

    for line in drift:
        print(line)
    if check and drift:
        print("harness wiring is out of date; run tools/sync-harness.py", file=sys.stderr)
        return 1
    if not drift:
        print("harness wiring up to date")
    return 0


if __name__ == "__main__":
    sys.exit(sync("--check" in sys.argv[1:]))
